baseURL: https://ffflorian.dev
title: Florian Imdahl
theme: PaperMod
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: false

params:
  env: production
  title: Florian Imdahl
  keywords: [Florian Imdahl, TypeScript, Rust, Go]
  author: Me
  socialIcons:
    - name: Mastodon
      url: https://chaos.social/@ffflorian
    - name: GitHub
      url: https://github.com/ffflorian
    - name: LinkedIn
      url: https://linkedin.com/in/ffflorian
    - name: Keyoxide
      url: https://keyoxide.org/5B9DCD6E60D3813E82753335BDAD14B04B98BD1A

languages:
  en:
    weight: 1
    languageCode: en-us
    languageName: 'English'
    displayFullLangName: true
    params:
      description: 'Florian Imdahl | Software developer @ Deutsche Bahn | Learning Go, Rust, and Kubernetes'
      profileMode:
        enabled: true
        title: Florian Imdahl
        imageUrl: /img/florian.jpg
        imageWidth: 200
        imageHeight: 200
        subtitle: 'Software developer @ [Deutsche Bahn](https://deutschebahn.com) | Learning [Go](https://golang.com), [Rust](https://www.rust-lang.org), and [Kubernetes](https://kubernetes.io)'
        imageTitle: Profile image of Florian Imdahl
    menu:
      main:
        - name: Photography
          url: photography
          weight: 1
  de:
    weight: 2
    languageCode: de-de
    languageName: 'Deutsch'
    displayFullLangName: true
    params:
      description: 'Florian Imdahl | Softwareentwickler @ Deutsche Bahn | Lerne aktuell Go, Rust und Kubernetes'
      profileMode:
        enabled: true
        title: Florian Imdahl
        imageUrl: /img/florian.jpg
        imageWidth: 200
        imageHeight: 200
        subtitle: 'Softwareentwickler @ [Deutsche Bahn](https://deutschebahn.com) | Lerne aktuell [Go](https://golang.com), [Rust](https://www.rust-lang.org) und [Kubernetes](https://kubernetes.io)'
        imageTitle: Profilbild von Florian Imdahl
    menu:
      main:
        - name: Fotografie
          url: photography
          weight: 1