baseURL: https://ffflorian.dev
languageCode: en-us
title: Florian Imdahl
theme: PaperMod

enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: false

params:
  env: production
  title: Florian Imdahl
  description: 'Florian Imdahl | Software developer @ Deutsche Bahn | Learning Go, Rust, and Kubernetes'
  keywords: [Florian Imdahl, TypeScript, Rust, Go]
  author: Me
  DateFormat: January 2, 2006

  profileMode:
    enabled: true
    title: Florian Imdahl
    subtitle: 'Software developer @ Deutsche Bahn | Learning Go, Rust, and Kubernetes'
    imageUrl: florian.jpg
    imageWidth: 200
    imageHeight: 200
    imageTitle: Profile image of Florian Imdahl
  socialIcons:
    - name: Mastodon
      url: https://chaos.social/@ffflorian
    - name: GitHub
      url: https://github.com/ffflorian
    - name: LinkedIn
      url: https://linkedin.com/in/ffflorian