name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
        with:
          go-version: stable

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f
        with:
          hugo-version: '0.145.0'

      - name: Build
        run: |
          hugo --minify
          touch ./public/.nojekyll

      - name: Deploy
        if: |
          github.event_name != 'pull_request' &&
          !startsWith(github.event.head_commit.message, 'chore(deps')
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f
        with:
          folder: public
          clean: true
          branch: gh-pages
