name: Deploy

permissions: {}

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy latest image
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Deploy
        uses: ffflorian/actions/coolify-deploy@bac55801ce13998bfa3e797f210c418e509a519e
        with:
          domain: ${{ secrets.COOLIFY_DOMAIN }}
          token: ${{ secrets.COOLIFY_TOKEN }}
          uuid: ${{ secrets.COOLIFY_UUID }}
