name: Update Hugo modules

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions: {}

jobs:
  hugo-theme-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: ffflorian/actions/hugo-theme-update@bac55801ce13998bfa3e797f210c418e509a519e
        with:
          git_authorship: Florian Imdahl <git@ffflorian.de>
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
